[Definition]
failregex = ^<HOST> - - \[.*\] "POST /login HTTP/.*" 200 .*Invalid username or password
            ^<HOST> - - \[.*\] "POST /login HTTP/.*" 401
            ^<HOST> - - \[.*\] "GET /api/.*" 401
ignoreregex =
